- type: entity
  id: STBasePrisonStationAlertLevels
  abstract: true
  components:
  - type: AlertLevel
    defaultAlertLevel: STPrisonGreen
    currentAlertLevel: STPrisonGreen
    availableAlertLevels:
    - STPrisonBlue
    - STPrisonDelta
    - STPrisonGamma
    - STPrisonGreen
    - STPrisonRed
    - STPrisonViolet
    - STPrisonYellow
