using System.Linq;
using System.Numerics;
using Content.Client._Stories.Sponsors;
using Content.Client.UserInterface.Controls;
using Content.Shared._Stories.SCCVars;
using Content.Shared._Stories.Sponsors;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Stories.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class SponsorPerksWindow : FancyWindow
{
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private SponsorsManager _sponsorsManager = default!;
    [Dependency] private IUriOpener _uriOpener = default!;

    private readonly SpriteSystem _spriteSystem;

    private static readonly ResPath DefaultGhostRsi = new("Mobs/Ghosts/ghost_human.rsi");
    private const string DefaultGhostState = "animated";

    public SponsorPerksWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Resizable = false;
        _spriteSystem = _entManager.System<SpriteSystem>();

        MainTabContainer.SetTabTitle(0, Loc.GetString("stories-sponsor-perks-tab"));
        MainTabContainer.SetTabTitle(1, Loc.GetString("stories-sponsor-ghost-skins-tab"));

        PerksText.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString("stories-sponsor-perks-description")));

        BoostyLinkButton.OnPressed += _ =>
        {
            var url = _cfg.GetCVar(CCVars.InfoLinksPatreon);
            if (!string.IsNullOrEmpty(url))
                _uriOpener.OpenUri(url);
        };

        PopulateGhostSkins();
    }

    private void PopulateGhostSkins()
    {
        GhostSkinsGrid.DisposeAllChildren();

        _sponsorsManager.TryGetInfo(out var sponsorInfo);
        var currentSkin = _cfg.GetCVar(SCCVars.SelectedGhostSkin);
        var isDefaultSelected = string.IsNullOrEmpty(currentSkin) || currentSkin.Equals("default", StringComparison.OrdinalIgnoreCase);

        var defaultSpecifier = new SpriteSpecifier.Rsi(DefaultGhostRsi, DefaultGhostState);
        AddSkinTile(
            protoId: string.Empty,
            tooltipTitle: Loc.GetString("stories-sponsor-ghost-skin-default"),
            spriteSpecifier: defaultSpecifier,
            isAllowed: true,
            isSelected: isDefaultSelected,
            onSelect: () => SelectSkin(string.Empty)
        );

        var skinEntries = new List<(EntityPrototype Proto, SponsorGhostSkinInfoComponent Info)>();
        foreach (var proto in _prototype.EnumeratePrototypes<EntityPrototype>())
        {
            if (proto.TryGetComponent<SponsorGhostSkinInfoComponent>(out var info, _entManager.ComponentFactory))
                skinEntries.Add((proto, info));
        }

        skinEntries.Sort((a, b) => string.Compare(a.Proto.ID, b.Proto.ID, StringComparison.Ordinal));

        foreach (var (proto, info) in skinEntries)
        {
            var isAllowed = sponsorInfo != null && sponsorInfo.AllowedGhostSkins.Any(allowed =>
                string.Equals(allowed, proto.ID, StringComparison.OrdinalIgnoreCase) ||
                string.Equals(allowed, "all", StringComparison.OrdinalIgnoreCase));

            var isSelected = !isDefaultSelected && string.Equals(currentSkin, proto.ID, StringComparison.OrdinalIgnoreCase);

            var specifier = info.Sprite ?? new SpriteSpecifier.Rsi(new ResPath("_Stories/Mobs/Ghosts/sponsor.rsi"), proto.ID);

            AddSkinTile(
                protoId: proto.ID,
                tooltipTitle: proto.ID,
                spriteSpecifier: specifier,
                isAllowed: isAllowed,
                isSelected: isSelected,
                onSelect: () => SelectSkin(proto.ID)
            );
        }
    }

    private void AddSkinTile(
        string protoId,
        string tooltipTitle,
        SpriteSpecifier spriteSpecifier,
        bool isAllowed,
        bool isSelected,
        Action onSelect)
    {
        Color bgColor;
        Color borderColor;
        int borderWidth;
        string statusHint;

        if (isSelected)
        {
            bgColor = Color.FromHex("#1f5223");
            borderColor = Color.FromHex("#4be05a");
            borderWidth = 2;
            statusHint = Loc.GetString("stories-sponsor-ghost-skins-selected");
        }
        else if (isAllowed)
        {
            bgColor = Color.FromHex("#222a3a");
            borderColor = Color.FromHex("#485f85");
            borderWidth = 1;
            statusHint = Loc.GetString("stories-sponsor-ghost-skins-select");
        }
        else
        {
            bgColor = Color.FromHex("#381c1c");
            borderColor = Color.FromHex("#612a2a");
            borderWidth = 1;
            statusHint = Loc.GetString("stories-sponsor-ghost-skins-locked");
        }

        var tooltip = $"{tooltipTitle}\n[{statusHint}]";

        var tileButton = new ContainerButton
        {
            SetSize = new Vector2(80, 80),
            MinSize = new Vector2(80, 80),
            ToolTip = tooltip,
            Disabled = !isAllowed || isSelected,
        };

        if (isAllowed && !isSelected)
            tileButton.DefaultCursorShape = CursorShape.Hand;

        var panel = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = bgColor,
                BorderColor = borderColor,
                BorderThickness = new Thickness(borderWidth),
            },
            MouseFilter = MouseFilterMode.Pass,
            HorizontalExpand = true,
            VerticalExpand = true,
        };
        tileButton.AddChild(panel);

        var icon = new TextureRect
        {
            Texture = _spriteSystem.Frame0(spriteSpecifier),
            SetSize = new Vector2(64, 64),
            MinSize = new Vector2(64, 64),
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            Stretch = TextureRect.StretchMode.KeepCentered,
            TextureScale = new Vector2(2, 2),
            MouseFilter = MouseFilterMode.Pass,
        };
        if (!isAllowed)
            icon.Modulate = Color.FromHex("#777777");

        panel.AddChild(icon);

        tileButton.OnPressed += _ => onSelect();

        GhostSkinsGrid.AddChild(tileButton);
    }

    private void SelectSkin(string skin)
    {
        _cfg.SetCVar(SCCVars.SelectedGhostSkin, skin);
        _cfg.SaveToFile();
        _sponsorsManager.SendGhostSkinSelection(skin);
        PopulateGhostSkins();
    }
}
