// Stories-Economy
using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.IdentityManagement;
using Content.Shared.Labels.Components;
using Content.Shared.VendingMachines;
using Robust.Client.AutoGenerated;
using Robust.Client.Input;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.VendingMachines.UI;

[GenerateTypedNameReferences]
public sealed partial class VendingMachineMenu : FancyWindow
{
    [Dependency] private IComponentFactory _componentFactory = default!;
    [Dependency] private ILocalizationManager _loc = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    private readonly Dictionary<VendorItemKey, (ListContainerButton Button, VendingMachineItem Item)> _listItems = new();
    private readonly Dictionary<VendorItemKey, uint> _amounts = new();

    public List<VendingMachineInventoryEntry> Inventory = new();

    /// <summary>
    /// Whether the vending machine is able to be interacted with or not.
    /// </summary>
    private bool _enabled;

    public event Action<GUIBoundKeyEventArgs, ListData>? OnItemSelected;

    public VendingMachineMenu()
    {
        MinSize = SetSize = new Vector2(350, 450);
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        VendingContents.SearchBar = SearchBar;
        VendingContents.DataFilterCondition += DataFilterCondition;
        VendingContents.GenerateItem += GenerateButton;
        VendingContents.ItemKeyBindDown += (args, data) => OnItemSelected?.Invoke(args, data);

        UpdateBalance(null);
    }

    private bool DataFilterCondition(string filter, ListData data)
    {
        if (data is not VendorItemsListData { ItemText: var text })
            return false;

        return string.IsNullOrEmpty(filter)
        || text.Contains(filter, StringComparison.CurrentCultureIgnoreCase);
    }

    private void GenerateButton(ListData data, ListContainerButton button)
    {
        if (data is not VendorItemsListData { ItemType: var type, ItemProtoID: var protoID, ItemText: var text, Amount: var amount })
            return;

        var item = new VendingMachineItem(protoID, text);
        var key = new VendorItemKey(type, protoID);
        _listItems[key] = (button, item);
        button.AddChild(item);
        button.AddStyleClass(StyleClass.ButtonSquare);

        var isOutOfStock = amount == 0;
        button.Disabled = !_enabled || isOutOfStock;
        if (isOutOfStock)
            item.Modulate = Color.Gray;
    }

    /// <summary>
    /// Populates the list of available items on the vending machine interface
    /// and sets icons based on their prototypes
    /// </summary>
    public void Populate(List<VendingMachineInventoryEntry> inventory, bool enabled = true)
    {
        Inventory = inventory;
        _enabled = enabled;
        _listItems.Clear();
        _amounts.Clear();

        if (inventory.Count == 0 && VendingContents.Visible)
        {
            SearchBar.Visible = false;
            VendingContents.Visible = false;

            var outOfStockLabel = new Label
            {
                Text = Loc.GetString("vending-machine-component-try-eject-out-of-stock"),
                Margin = new Thickness(4, 4),
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Stretch,
                HorizontalAlignment = HAlignment.Center
            };

            MainContainer.AddChild(outOfStockLabel);

            SetSizeAfterUpdate(outOfStockLabel.Text.Length, 0);

            return;
        }

        var longestEntry = string.Empty;
        var listData = new List<ListData>();

        for (var i = 0; i < inventory.Count; i++)
        {
            var entry = inventory[i];

            if (!_prototypeManager.Resolve(entry.ID, out var prototype))
            {
                _amounts[new VendorItemKey(entry.Type, entry.ID)] = 0;
                continue;
            }

            var itemText = GetItemText(prototype, entry.Amount, entry.Price);
            var key = new VendorItemKey(entry.Type, prototype.ID);
            _amounts[key] = entry.Amount;

            if (itemText.Length > longestEntry.Length)
                longestEntry = itemText;

            listData.Add(new VendorItemsListData(entry.Type, prototype.ID, i)
            {
                ItemText = itemText,
                Price = entry.Price,
                Amount = entry.Amount,
            });
        }

        VendingContents.PopulateList(listData);

        SetSizeAfterUpdate(longestEntry.Length, inventory.Count);
    }

    /// <summary>
    /// Updates text entries for vending data in place without modifying the list controls.
    /// </summary>
    public void UpdateAmounts(List<VendingMachineInventoryEntry> cachedInventory, bool enabled)
    {
        _enabled = enabled;

        foreach (var (key, (button, item)) in _listItems)
        {
            if (!cachedInventory.TryFirstOrDefault(o => o.Type == key.Type && o.ID == key.Prototype, out var entry))
                continue;

            if (!_prototypeManager.Resolve(key.Prototype, out var prototype))
                continue;

            var amount = entry.Amount;
            _amounts[key] = amount;

            var text = GetItemText(prototype, amount, entry.Price);

            item.SetText(text);
            var isOutOfStock = amount == 0;
            button.Disabled = !enabled || isOutOfStock;
            item.Modulate = isOutOfStock ? Color.Gray : Color.White;
        }
    }

    public void SetButtonsDisabled(bool disabled)
    {
        _enabled = !disabled;
        foreach (var (key, (button, item)) in _listItems)
        {
            var isOutOfStock = _amounts.TryGetValue(key, out var amount) && amount == 0;
            button.Disabled = disabled || isOutOfStock;
        }
    }

    public void UpdateBalance(int? balance)
    {
        if (balance.HasValue)
        {
            BalanceLabel.Text = Loc.GetString("stories-vending-machine-ui-balance", ("balance", balance.Value));
        }
        else
        {
            BalanceLabel.Text = Loc.GetString("stories-vending-machine-ui-balance", ("balance", Loc.GetString("stories-vending-machine-ui-no-balance")));
        }
    }

    private string GetItemText(EntityPrototype prototype, uint amount, uint price)
    {
        var itemName = prototype.Name;

        if (prototype.TryComp<LabelComponent>(out var label, _componentFactory) &&
            label.LocalizedLabel is { } locId)
        {
            itemName = _loc.GetString("comp-label-format",
                ("baseName", itemName),
                ("label", _loc.GetString(locId)));
        }

        if (price > 0)
        {
            return Loc.GetString("stories-vending-machine-item-entry-with-price",
                ("name", itemName),
                ("amount", amount),
                ("price", price));
        }

        return Loc.GetString("stories-vending-machine-item-entry-no-price",
            ("name", itemName),
            ("amount", amount));
    }

    private void SetSizeAfterUpdate(int longestEntryLength, int contentCount)
    {
        SetSize = new Vector2(Math.Clamp((longestEntryLength + 2) * 12, 250, 400),
            Math.Clamp(contentCount * 50, 150, 350));
    }
}

public record VendorItemsListData(InventoryType ItemType, EntProtoId ItemProtoID, int ItemIndex) : ListData
{
    public string ItemText = string.Empty;
    public uint Price;
    public uint Amount;
}

public readonly record struct VendorItemKey(InventoryType Type, EntProtoId Prototype);
