using System.Linq;
using Content.Client._Stories.Lobby.UI;
using Content.Shared._Stories.TTS;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Administration.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class AdminAnnounceWindow : DefaultWindow
    {
        [Dependency] private ILocalizationManager _localization = default!;
        // Stories-TTS-Start
        [Dependency] private IPrototypeManager _proto = default!;

        public string? SelectedVoice { get; private set; }
        private TTSVoiceSelectionWindow? _voiceWindow;
        // Stories-TTS-End

        public AdminAnnounceWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            Announcement.Placeholder = new Rope.Leaf(_localization.GetString("admin-announce-announcement-placeholder"));
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-station"));
            AnnounceMethod.SetItemMetadata(0, AdminAnnounceType.Station);
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-server"));
            AnnounceMethod.SetItemMetadata(1, AdminAnnounceType.Server);
            AnnounceMethod.OnItemSelected += AnnounceMethodOnOnItemSelected;
            Announcement.OnKeyBindUp += AnnouncementOnOnTextChanged;

            // Stories-TTS-Start
            VoiceButton.OnPressed += OnVoiceButtonPressed;
            ResetVoiceButton.OnPressed += _ =>
            {
                SelectedVoice = null;
                UpdateVoiceButton();
            };

            UpdateVoiceButton();
            // Stories-TTS-End
        }

        // Stories-TTS-Start
        private void UpdateVoiceButton()
        {
            if (string.IsNullOrEmpty(SelectedVoice))
            {
                VoiceButton.Text = _localization.GetString("stories-admin-announce-voice-default");
                return;
            }

            if (_proto.TryIndex<TTSVoicePrototype>(SelectedVoice, out var proto))
            {
                VoiceButton.Text = proto.Name;
            }
            else
            {
                VoiceButton.Text = SelectedVoice;
            }
        }

        private void OnVoiceButtonPressed(BaseButton.ButtonEventArgs args)
        {
            if (_voiceWindow != null)
            {
                _voiceWindow.MoveToFront();
                return;
            }

            var voices = _proto.EnumeratePrototypes<TTSVoicePrototype>()
                .Select(v => (v, true))
                .ToList();

            _voiceWindow = new TTSVoiceSelectionWindow(voices, SelectedVoice);
            _voiceWindow.OnVoiceSelected += voiceId =>
            {
                SelectedVoice = voiceId;
                UpdateVoiceButton();
            };
            _voiceWindow.OnClose += () => _voiceWindow = null;
            _voiceWindow.OpenCentered();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (disposing)
            {
                _voiceWindow?.Close();
                _voiceWindow = null;
            }
        }
        // Stories-TTS-End

        private void AnnouncementOnOnTextChanged(GUIBoundKeyEventArgs args)
        {
            AnnounceButton.Disabled = Rope.Collapse(Announcement.TextRope).TrimStart() == "";
        }

        private void AnnounceMethodOnOnItemSelected(OptionButton.ItemSelectedEventArgs args)
        {
            AnnounceMethod.SelectId(args.Id);
            Announcer.Editable = ((AdminAnnounceType?)args.Button.SelectedMetadata ?? AdminAnnounceType.Station) == AdminAnnounceType.Station;
        }
    }
}
