- type: job
  id: STIAA
  name: job-name-iaa
  description: job-description-iaa
  playTimeTracker: STJobIAA
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 10h
  - !type:DepartmentTimeRequirement
    department: Command
    time: 5h
  - !type:DepartmentTimeRequirement
    department: Security
    time: 5h
  startingGear: STIAAGear
  icon: "STJobIconIAA"
  supervisors: job-supervisors-centcom
  access:
  - Service
  - Brig
  - Maintenance
  - Command
  - External
  - Lawyer
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  minBankBalance: 250
  maxBankBalance: 300

- type: startingGear
  id: STIAAGear
  equipment:
    id: STIAAPDA
    eyes: ClothingEyesGlassesSunglasses
    ears: STClothingHeadsetIAA
  inhand:
    - BriefcaseBrown
  storage:
    back:
    - STRubberStampIAA

- type: chameleonOutfit
  id: STIAAChameleonOutfit
  job: STIAA
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBowlerHat
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckLawyerbadge
    outerClothing: ClothingOuterWinterColorBlack
    gloves: ClothingHandsGlovesColorBlack
