- type: startingGear
  id: STInquisitorGear
  equipment:
    jumpsuit: STClothingUniformJumpsuitInquisitor
    mask: STClothingMaskGasInquisitor
    neck: STClothingNeckCloakInquisitor
    eyes: ClothingEyesHudSyndicate
    gloves: STClothingHandsGlovesInquisitor
    outerClothing: STClothingOuterVestInquisitor
    shoes: ClothingShoesInquisitor
    id: AgentIDCard
    back: JetpackBlackFilled
    ears: ClothingHeadsetGrey
    pocket1: STLightsaberDoubleRed
    pocket2: PinpointerUniversal
    belt: STClothingBeltInquisitor

- type: startingGear
  id: STKyloGear
  equipment:
    jumpsuit: STClothingUniformJumpsuitKylo
    mask: ClothingMaskGasSyndicate
    neck: STClothingNeckCloakKylo
    gloves: ClothingHandsGlovesCombat
    outerClothing: STClothingOuterVestInquisitor
    shoes: ClothingShoesInquisitor
    id: AgentIDCard
    back: JetpackBlackFilled
    ears: ClothingHeadsetGrey
    pocket1: STLightsaberCrossguardRed
    pocket2: PinpointerUniversal
    belt: STClothingBeltInquisitor
