- type: job
  id: STPRISONHeadOfPrison
  name: stories-job-name-head-of-prison
  description: stories-job-description-head-of-prison
  playTimeTracker: STJobHeadOfSpacePrison
  setPreference: false
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 20h
    - !type:DepartmentTimeRequirement
      department: Prison
      time: 10h
    - !type:RoleTimeRequirement
      role: STJobSpacePrisonOfficer
      time: 2h
  startingGear: STPRISONHeadOfPrisonGear
  icon: "STJobIconHeadOfSpacePrison"
  requireAdminNotify: true
  supervisors: job-supervisors-centcom
  accessGroups:
  - STPrisonAllAccess
  access:
  - Command
  - Armory
  - Bar
  - Brig
  - Security
  - Maintenance
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  minBankBalance: 300
  maxBankBalance: 350

- type: startingGear
  id: STPRISONHeadOfPrisonGear
  storage:
    back:
    - WeaponPistolMk58
    - Flash
    - MagazinePistol
  equipment:
    jumpsuit: STPRISONClothingUniformJumpsuitHeadOfPrison
    id: STPRISONPDAHeadOfPrison
    ears: STPRISONClothingHeadsetAlt
    outerClothing: STPRISONClothingOuterCoatHeadOfPrison
    eyes: STPRISONClothingEyesGlasses
    belt: STPRISONClothingBeltSheathFilled

- type: chameleonOutfit
  id: STPRISONHeadOfPrisonChameleonOutfit
  job: STPRISONHeadOfPrison
  hasMindShield: true
  equipment:
    mask: ClothingMaskGasSecurity
    neck: Dinkystar
