- type: job
  id: STPRISONPrisoner
  name: stories-job-name-prisoner
  playTimeTracker: STJobPrisoner
  setPreference: false
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 2h
  description: stories-job-description-prisoner
  startingGear: STPRISONPrisoner
  icon: "STJobIconPRISONPrisoner"
  supervisors: job-supervisors-everyone
  access:
  - Prisoner
  special:
  - !type:AddComponentSpecial
    components:
    - type: Prisoner
  minBankBalance: 0
  maxBankBalance: 0

- type: startingGear
  id: STPRISONPrisoner
  equipment:
    id: STPRISONIDCardPrisoner
    jumpsuit: ClothingUniformJumpsuitPrisoner
    shoes: ClothingShoesColorBlack
