- type: job
  id: STPRISONPrisoner
  name: заключенный космической тюрьмы
  playTimeTracker: STJobPrisoner
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 7200 # 2 hours
  description: Как я сюда попал?
  startingGear: STPRISONPrisoner
  icon: "STJobIconPRISONPrisoner"
  supervisors: job-supervisors-everyone
  access:
  - Prisoner
  special:
  - !type:AddComponentSpecial
    components:
    - type: Prisoner
  minBankBalance: 0
  maxBankBalance: 0

- type: startingGear
  id: STPRISONPrisoner
  equipment:
    id: STPRISONIDCardPrisoner
    jumpsuit: ClothingUniformJumpsuitPrisoner
    shoes: ClothingShoesColorBlack
