- type: job
  id: STPRISONMedic
  name: stories-job-name-prison-medic
  description: stories-job-description-prison-medic
  playTimeTracker: STJobSpacePrisonMedic
  setPreference: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 2h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 1h
  startingGear: STPRISONMedicGear
  icon: "STJobIconSpacePrisonMedic"
  supervisors: stories-job-supervisors-headofprison
  access:
  - Prisoner
  - Prison
  - STPrisonMed
  - Maintenance
  # special:
  # - !type:AddImplantSpecial
  #   implants: [ MindShieldImplant ]
  minBankBalance: 200
  maxBankBalance: 250

- type: startingGear
  id: STPRISONMedicGear
  equipment:
    jumpsuit: STPRISONClothingUniformJumpsuitMedic
    id: STPRISONPDAMedic
    ears: STPRISONClothingHeadsetMedic

- type: chameleonOutfit
  id: STPRISONMedicChameleonOutfit
  job: STPRISONMedic
  equipment:
    head: ClothingHeadHatBeretMedic
    gloves: ClothingHandsGlovesLatex
    mask: ClothingMaskBreathMedical
    eyes: ClothingEyesChameleon
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatLab
