- type: job
  id: STPRISONEngineer
  name: stories-job-name-prison-engineer
  description: stories-job-description-prison-engineer
  playTimeTracker: STJobSpacePrisonEngineer
  setPreference: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 2h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 1h
  startingGear: STPRISONEngineerGear
  icon: "STJobIconSpacePrisonEngineer"
  supervisors: stories-job-supervisors-headofprison
  access:
  - Prisoner
  - Prison
  - STPrisonEng
  - Maintenance
  - External
  # special:
  # - !type:AddImplantSpecial
  #   implants: [ MindShieldImplant ]
  minBankBalance: 200
  maxBankBalance: 250

- type: startingGear
  id: STPRISONEngineerGear
  equipment:
    jumpsuit: STPRISONClothingUniformJumpsuitEngi
    id: STPRISONPDAEngineer
    ears: STPRISONClothingHeadsetEngi
    belt: ClothingBeltUtilityEngineering

- type: chameleonOutfit
  id: STPRISONEngineerChameleonOutfit
  job: STPRISONEngineer
  equipment:
    head: ClothingHeadHatHardhatYellow
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedOrange
    gloves: ClothingHandsGlovesColorYellow
    eyes: ClothingEyesGlassesMeson
