- type: job
  id: STPRISONOfficer
  name: офицер космической тюрьмы
  description: Ограждать станцию от преступного элемента - это ваша наивысшая миссия на смену, не подведите.
  playTimeTracker: STJobSpacePrisonOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 # 5 hours
  startingGear: STPRISONOfficerGear
  icon: "STJobIconSpacePrisonOfficer"
  supervisors: stories-job-supervisors-headofprison
  access:
  - Prisoner
  - Prison
  - STPrisonBrig
  - Security
  - Brig
  - Maintenance
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  minBankBalance: 200
  maxBankBalance: 250

- type: startingGear
  id: STPRISONOfficerGear
  storage:
    back:
    - WeaponPistolMk58
    - MagazinePistol
    - Flash
  equipment:
    jumpsuit: STPRISONClothingUniformJumpsuit
    id: STPRISONPDAOfficer
    ears: STPRISONClothingHeadset
    eyes: STPRISONClothingEyesGlasses

- type: chameleonOutfit
  id: STPRISONOfficerChameleonOutfit
  job: STPRISONOfficer
  hasMindShield: true
  equipment:
    head: STPRISONClothingHeadHatBeret
    mask: ClothingMaskGasSecurity
    neck: Dinkystar
