- type: job
  id: STPRISONEngineer
  name: инженер космической тюрьмы
  description: Обслуживайте тюрьму, ибо сбежавшие зеки придут за вами в первую очередь.
  playTimeTracker: STJobSpacePrisonEngineer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 # 5 hours
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 18000 # 5 hours
  startingGear: STPRISONEngineerGear
  icon: "STJobIconSpacePrisonEngineer"
  supervisors: stories-job-supervisors-headofprison
  access:
  - Prisoner
  - Prison
  - STPrisonEng
  - Maintenance
  - External
  # special:
  # - !type:AddImplantSpecial
  #   implants: [ MindShieldImplant ]
  minBankBalance: 200
  maxBankBalance: 250

- type: startingGear
  id: STPRISONEngineerGear
  equipment:
    jumpsuit: STPRISONClothingUniformJumpsuitEngi
    id: STPRISONPDAEngineer
    ears: STPRISONClothingHeadsetEngi
    belt: ClothingBeltUtilityEngineering

- type: chameleonOutfit
  id: STPRISONEngineerChameleonOutfit
  job: STPRISONEngineer
  equipment:
    head: ClothingHeadHatHardhatYellow
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedOrange
    gloves: ClothingHandsGlovesColorYellow
    eyes: ClothingEyesGlassesMeson
