- type: job
  id: STGuardianNt
  name: stories-job-name-guardian-nt
  description: stories-job-description-guardian-nt
  playTimeTracker: STJobGuardianNt
  setPreference: false
  requirements:
    - !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 36000 # 10 hours
    - !type:RoleTimeRequirement
      role: JobCaptain
      time: 36000 # 10 hours
    - !type:RoleTimeRequirement
      role: STJobIAA
      time: 36000 # 10 hours # ! Почему так чертовски много?
    - !type:RoleTimeRequirement
      role: JobDetective
      time: 18000 # 5 hours
  startingGear: STGuardianNtGear
  icon: "STJobIconGuardianNt"
  supervisors: job-supervisors-centcom
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: Force
    - type: ForceUser
      preset: Guardian
  minBankBalance: 250
  maxBankBalance: 300

- type: startingGear
  id: STGuardianNtGear
  equipment:
    id: STGuardianNtPDA
    ears: STClothingHeadsetGuardianNtAlt
    gloves: ClothingHandsGlovesCombat
    eyes: ClothingEyesGlassesSecurity

- type: chameleonOutfit
  id: STGuardianNtChameleonOutfit
  job: STGuardianNt
  hasMindShield: true
  equipment:
    head: STClothingHeadHatExe
    mask: STClothingMaskGasExe
    neck: STClothingNeckMantleGuardianNt
    outerClothing: STClothingOuterVestGuardianNt
    jumpsuit: STClothingUniformJumpsuitGuardianNt
    back: STClothingBackpackGuardianNt
    shoes: STClothingShoesBootsJackGuardianNt
