- type: entity
  abstract: true
  id: STBaseMachineBeerUnprotected
  components:
  # Stories-Beer-Emp
  - type: Reactive
    groups:
      Flammable: [Touch]
      Extinguish: [Touch]
      Acidic: [Touch, Ingestion]
    reactions:
    - reagents: [ Beer ]
      methods: [ Touch ]
      effects:
      - !type:EmpReactionEffect
        maxRange: 0.1
  - type: DisableOnEmp
  # Stories-Beer-Emp
