- type: entity
  id: STPrinterDocMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: бумажный принтер (машинная плата)
  description: Печатна плата для бумажного принтера.
  components:
  - type: MachineBoard
    prototype: STPrinterDoc
    stackRequirements:
      Manipulator: 4
      Glass: 1

- type: entity
  id: STReflectorBoxMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Reflector, type "Box"
  description: Reflector machine board, type "Box"
  components:
  - type: Sprite
    sprite: _Stories/Objects/Misc/module.rsi
    state: reflectorbox_circuitboard
  - type: MachineBoard
    prototype: STReflectorBox
    stackRequirements:
      Manipulator: 3
      CableHV: 10
    componentRequirements:
      PowerCell:
        amount: 1
        defaultPrototype: PowerCellMedium

- type: entity
  id: STReflectorCornerMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Reflector, type "Corner"
  description: Reflector machine board, type "Corner"
  components:
  - type: Sprite
    sprite: _Stories/Objects/Misc/module.rsi
    state: reflectorcorner_circuitboard
  - type: MachineBoard
    prototype: STReflectorCorner
    stackRequirements:
      Manipulator: 3
      CableHV: 10
    componentRequirements:
      PowerCell:
        amount: 1
        defaultPrototype: PowerCellMedium

- type: entity
  id: STReflectorCornerTsideMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Reflector, type "Double-Corner"
  description: Reflector machine board, type "Double-Corner"
  components:
  - type: Sprite
    sprite: _Stories/Objects/Misc/module.rsi
    state: reflectortsidecorner_circuitboard
  - type: MachineBoard
    prototype: STReflectorCornerTside
    stackRequirements:
      Manipulator: 3
      CableHV: 10
    componentRequirements:
      PowerCell:
        amount: 1
        defaultPrototype: PowerCellMedium

