using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Content.Shared._Stories.SCCVars;
using Content.Shared.Radio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client.Options.UI.Tabs
{
    [GenerateTypedNameReferences]
    public sealed partial class TTSTab : Control
    {
        [Dependency] private IConfigurationManager _cfg = default!;
        [Dependency] private IPrototypeManager _proto = default!;

        public TTSTab()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            Control.AddOptionCheckBox(SCCVars.TTSEnabledClient, TtsEnabledCheckBox);

            Control.AddOptionPercentSlider(
                SCCVars.TTSVolumeMaster,
                SliderVolumeMasterTTS);

            Control.AddOptionPercentSlider(
                SCCVars.TTSVolumeAnnounce,
                SliderVolumeAnnounce);

            Control.AddOptionPercentSlider(
                SCCVars.TTSVolumeNearby,
                SliderVolumeNearby);

            Control.AddOptionPercentSlider(
                SCCVars.TTSVolumeRadio,
                SliderVolumeRadio);

            var channels = _proto.EnumeratePrototypes<RadioChannelPrototype>()
                .Where(c => c.ShowInTTSOptions)
                .GroupBy(c => c.TtsCategory ?? "stories-tts-category-radio-other")
                .OrderBy(g => Loc.GetString(g.Key));

            foreach (var group in channels)
            {
                var label = new Label
                {
                    Text = Loc.GetString(group.Key),
                    StyleClasses = { "LabelKeyText" },
                    Margin = new Robust.Shared.Maths.Thickness(0, 10, 0, 5)
                };
                RadioVolumesContainer.AddChild(label);

                foreach (var channel in group.OrderBy(c => Loc.GetString(c.Name)))
                {
                    var slider = new OptionSlider
                    {
                        Title = Loc.GetString(channel.Name),
                        TextColor = channel.Color
                    };
                    RadioVolumesContainer.AddChild(slider);

                    Control.AddOption(new OptionRadioVolume(Control, _cfg, slider, channel.ID));
                }
            }

            Control.Initialize();
        }

        private sealed class OptionRadioVolume : BaseOption
        {
            private readonly IConfigurationManager _cfg;
            private readonly OptionSlider _slider;
            private readonly string _channelId;

            public OptionRadioVolume(OptionsTabControlRow controller, IConfigurationManager cfg, OptionSlider slider, string channelId) : base(controller)
            {
                _cfg = cfg;
                _slider = slider;
                _channelId = channelId;

                slider.Slider.MinValue = 0;
                slider.Slider.MaxValue = 1;
                slider.Slider.OnValueChanged += _ =>
                {
                    ValueChanged();
                    UpdateLabelValue();
                };
            }

            public override void LoadValue()
            {
                var val = GetCurrentValue();
                _slider.Slider.Value = val;
                UpdateLabelValue();
            }

            public override void SaveValue()
            {
                var dict = GetVolumesDictionary();
                dict[_channelId] = _slider.Slider.Value;
                SaveVolumesDictionary(dict);
            }

            public override void ResetToDefault()
            {
                _slider.Slider.Value = _cfg.GetCVar(SCCVars.TTSVolumeRadio);
                UpdateLabelValue();
            }

            public override bool IsModified()
            {
                return Math.Abs(_slider.Slider.Value - GetCurrentValue()) > 0.001f;
            }

            public override bool IsModifiedFromDefault()
            {
                return Math.Abs(_slider.Slider.Value - _cfg.GetCVar(SCCVars.TTSVolumeRadio)) > 0.001f;
            }

            private void UpdateLabelValue()
            {
                _slider.ValueLabel.Text = string.Format(CultureInfo.InvariantCulture, "{0:P0}", _slider.Slider.Value);
            }

            private float GetCurrentValue()
            {
                var dict = GetVolumesDictionary();
                if (dict.TryGetValue(_channelId, out var val))
                    return val;
                return _cfg.GetCVar(SCCVars.TTSVolumeRadio);
            }

            private Dictionary<string, float> GetVolumesDictionary()
            {
                var dict = new Dictionary<string, float>();
                var str = _cfg.GetCVar(SCCVars.TTSRadioVolumes);
                if (string.IsNullOrWhiteSpace(str))
                    return dict;

                var pairs = str.Split(';');
                foreach (var pair in pairs)
                {
                    var kv = pair.Split('=');
                    if (kv.Length == 2 && float.TryParse(kv[1], CultureInfo.InvariantCulture, out var val))
                    {
                        dict[kv[0]] = val;
                    }
                }
                return dict;
            }

            private void SaveVolumesDictionary(Dictionary<string, float> dict)
            {
                var str = string.Join(";", dict.Select(kv => $"{kv.Key}={kv.Value.ToString(CultureInfo.InvariantCulture)}"));
                _cfg.SetCVar(SCCVars.TTSRadioVolumes, str);
            }
        }
    }
}
