- type: gameMapPool
  id: StoriesDefaultMapPool
  maps:
  - StoriesBagel
  - StoriesBeta
  - StoriesBox
  - StoriesFland
  - StoriesKilo
  - StoriesLima
  - StoriesMeta
  - StoriesCore
  - StoriesOmega
  - CorvaxDelta
  - StoriesElkridge
