- type: gameMapPool
  id: STDefaultMapPool
  maps:
  - STBagel
  - STBox
  - STElkridge
  - STExo
  - STMarathon
  - STPacked
  - STPlasma
  - STSaltern
  - STSnowball
  - STSushi
  - STTram2
  # Старый маппул, удалён из за объёма работы требующися для переработки карт которые он содержит.
  # - STBagel
  # - STBeta
  # - STBox
  # - STFland
  # - STKilo
  # - STLima
  # - STMeta
  # - STOmega
  # - STCorvaxDelta
  # - STElkridge
  # - STSaltern
  # - STHelios
