- type: gameMapPool
  id: STDefaultMapPool
  maps:
  - STBagel
  - STBeta
  - STBox
  - STFland
  - STKilo
  - STLima
  - STMeta
  - STOmega
  - STCorvaxDelta
  - STElkridge
  - STSaltern
  - STHelios
