using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class LobbyCharacterPreviewPanel : Control
{
    public Button CharacterSetupButton => CharacterSetup;

    public LobbyCharacterPreviewPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetLoaded(bool value)
    {
        Loaded.Visible = value;
        Unloaded.Visible = !value;
    }

    public void SetSummaryText(string value)
    {
        Summary.Text = value;
    }

    // Stories-Sponsors-Start
    public void SetSponsor(string? title, string? hexColor)
    {
        if (string.IsNullOrEmpty(title))
        {
            SponsorTitle.Visible = false;
            return;
        }

        SponsorTitle.Visible = true;
        var colorTag = string.IsNullOrEmpty(hexColor) ? "Gold" : hexColor;
        SponsorTitle.SetMessage(FormattedMessage.FromMarkupPermissive($"[color={colorTag}][bold]{title}[/bold][/color]"));
    }
    // Stories-Sponsors-End
}
