# ATLAS CONFIG

# [config]
# presets = "Stories/atlas"

[adminlogs]
server_name = "Space Stories - Atlas 🗺️"

[game]
hostname         = "📚 Space Stories - Atlas 🗺️ [TTS]"
soft_max_players = 100

[hub]
tags = "lang:ru,rp:med,region:eu_e"
