# DEVELOP CONFIG

# [config]
# presets = "Stories/develop"

[whitelist]
enabled = true

[adminlogs]
enabled = false

[game]
hostname = "📚 Space Stories - Develop ⚙"
role_timers = false
desc = "⚙️ Это сервер 𝗦𝗽𝗮𝗰𝗲 𝗦𝘁𝗼𝗿𝗶𝗲𝘀 для разработчиков."

[rules]
time = 0.0
