# MAPPERS CONFIG

# [config]
# presets = "Stories/mappers"

[whitelist]
enabled = true
reason = "Требуется разрешение на подключение к этому серверу."

[adminlogs]
enabled = false

[game]
hostname = "📚 Space Stories - Mappers 🗺"
role_timers = false
desc = "⚙️ Это сервер 𝗦𝗽𝗮𝗰𝗲 𝗦𝘁𝗼𝗿𝗶𝗲𝘀 для мапперов."

[rules]
time = 0.0
