# Предустановка конфигурации, используемая на сервере Space Stories Stage.
# Загружается перед настройками конфигурации, специфичными для сервера.

# [config]
# presets = "Stories/stage"

[admin]
admins_count_in_playercount = true
deadmin_on_join = false

[adminlogs]
enabled = false

[game]
hostname = "📚 Space Stories - Stage ⚙"
desc = """
                  📕 𝗦𝗽𝗮𝗰𝗲 𝗦𝘁𝗼𝗿𝗶𝗲𝘀 - Сервер, который ценит Role Play, создавай свои истории у нас! 📘
•────────────────────────────────── ✧ ──────────────────────────────────•
  👥 ⋮ Сервер для персонала проекта Space Stories 📚
•────────────────────────────────── ✧ ──────────────────────────────────•
                                            📚 Присоединяйтесь к нашему дружному сообществу 📚"""
maxplayers = 10
soft_max_players = 10
role_timers = false
role_whitelist = false

[whitelist]
enabled = true

[rules]
time = 0.0
