# Базовая предустановка конфигурации, используемая на всех серверах Space Stories.
# Загружается перед настройками конфигурации, специфичными для сервера.

# [config]
# presets = "Stories/stories"

[admin]
deadmin_on_join = true
new_player_threshold = 600
role_ban_default_severity = "high"
department_ban_default_severity = "high"
server_ban_default_severity = "high"
server_ban_hwid_ban_default = false

[ahelp]
admin_prefix = true
admin_prefix_webhook = true

[auth]
mode = 1

[biomass]
easy_mode = false

[chat]
rate_limit_period = 1
rate_limit_count = 1
rate_limit_announce_admins_delay = 10
max_message_length = 500

[game]
contraband_examine = false
round_restart_time = 120
lobbyduration = 210
map_pool = "StoriesDefaultMapPool"
secret_weight_prototype = "StoriesSecret"

[gateway]
generator_enabled = false

[hub]
tags = "lang:ru,rp:med,region:eu_e"

[ic]
flavor_text = true

[infolinks]
bug_report = "https://github.com/MetalSage/space-stories-14/issues/new/choose"
discord = "https://discord.gg/space-stories"
forum = "https://forum.spacestories.club"
github = "https://github.com/MetalSage/space-stories-14"
patreon = "https://boosty.to/spacestories14"
wiki = "https://spacestories.club"
appeal = "https://discord.gg/space-stories"

[net]
tickrate = 25

[procgen]
preload = false

[queue]
enabled = true

[server]
rules_file = "StoriesRuleset"

[movement]
mob_pushing = true

[shuttle]
auto_call_time = 0
emergency_dock_time = 120
emergency_transit_time_min = 60
emergency_transit_time_max = 120

[vote]
restart_enabled = true
preset_enabled = false
map_enabled = false
restart_not_allowed_when_admin_online = true

[viewport]
maximum_width = 26
