# UNIVERSE CONFIG

# [config]
# presets = "Stories/universe"

[adminlogs]
server_name = "Space Stories - Universe 👩‍🚀"

[game]
hostname         = "📚 Space Stories - Universe 👩‍🚀 [TTS]"
soft_max_players = 130

[hub]
tags = "lang:ru,rp:med,region:eu_e"
