# Предустановка конфигурации, используемая на сервере Space Stories Universe.
# Загружается перед настройками конфигурации, специфичными для сервера.

# [config]
# presets = "Stories/universe"

[adminlogs]
server_name = "Space Stories - Universe 👩‍🚀"

[game]
hostname = "📚 Space Stories - Universe 👩‍🚀 [TTS]"
desc = """
                  📕 𝗦𝗽𝗮𝗰𝗲 𝗦𝘁𝗼𝗿𝗶𝗲𝘀 - Сервер, который ценит Role Play, создавай свои истории у нас! 📘
•────────────────────────────────── ✧ ──────────────────────────────────•
  🌠 ⋮ Сервер со средним уровнем требований к ролевому отыгрышу.
  🔐 ⋮ Космическая тюрьма - отдаленный объект в космосе, содержащий опасных преступников.
  🌑 ⋮ Тенеморф - полубог, боящийся света, порабощающий экипаж с целью захватить галактику.
  ⚔️ ⋮ Страж Клинка - воин света, защищающий командование станции своими мечом и магией.
  🔥  ⋮ Инквизитор - воин тьмы, прибывший на станцию, чтобы уничтожить Стража Клинка.
  🦠 ⋮ S.P.A.F. - слизень, пожирающий членов экипажа ради продолжения своего рода.
  🔊 ⋮ TTS - 130 уникальных голосов, чтобы выразить уникальность ваших персонажей.
  🐌 ⋮ Ползание - уникальная механика, позволяющая вам упасть и ползти.
  👔 ⋮ Отзывчивая администрация, которая покажет, расскажет и поможет Вам освоится.
•────────────────────────────────── ✧ ──────────────────────────────────•
                                            📚 Присоединяйтесь к нашему дружному сообществу 📚"""
maxplayers = 230
soft_max_players = 130
