- type: job
  id: PartyMaker
  name: stories-job-name-party-maker
  description: stories-job-description-party-maker
  playTimeTracker: JobPartyMaker
  startingGear: PartyMakerGear
  icon: "JobIconPartyMaker"
  supervisors: job-supervisors-hop
  setPreference: false
  access:
  - Service
  - Maintenance
  - Theatre

- type: startingGear
  id: PartyMakerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHawaiBlack
    id: PartyMakerPDA
    ears: ClothingHeadsetService
    eyes: ClothingEyesGlassesSunglasses
    shoes: ClothingShoesColorBlack
  storage:
    back:
    - SuperSynthesizerInstrument
