- type: antag
  id: STEmpireMember
  name: stories-roles-antag-empire-member-name
  antagonist: true
  setPreference: false
  objective: stories-roles-antag-empire-member-objective
  requirements:
  - !type:RoleTimeRequirement
    role: JobHeadOfSecurity
    time: 36000 # 10 hours
  - !type:RoleTimeRequirement
    role: JobCaptain
    time: 36000 # 10 hours
  - !type:RoleTimeRequirement
    role: STJobIAA
    time: 36000 # 10 hours
  - !type:RoleTimeRequirement
    role: JobDetective
    time: 18000 # 5 hours

- type: antag
  id: STHypnotizedEmpireMember
  name: stories-roles-antag-hypnotized-empire-member-name
  antagonist: true
  setPreference: false
  objective: stories-roles-antag-hypnotized-empire-member-objective
