- type: antag
  id: STEmpireMember
  name: stories-roles-antag-empire-member-name
  antagonist: true
  setPreference: false
  objective: stories-roles-antag-empire-member-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 5h

- type: antag
  id: STHypnotizedEmpireMember
  name: stories-roles-antag-hypnotized-empire-member-name
  antagonist: true
  setPreference: false
  objective: stories-roles-antag-hypnotized-empire-member-objective
