- type: antag
  id: Pontific
  name: roles-antag-pontific-name
  antagonist: true
  setPreference: true
  objective: roles-antag-pontific-objective
  guides: [ Pontific ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 72000 # 10h Stories-RoleTime
