using System.Linq;
using Content.Client.Resources;
using Content.Client.UserInterface.Controls;
using Content.Shared._Stories.PrisonerCollar;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics;
using Robust.Shared.Prototypes;

namespace Content.Client._Stories.PrisonerCollar;

[GenerateTypedNameReferences]
public sealed partial class PrisonerCollarConsoleWindow : FancyWindow
{
    private static readonly ProtoId<ShaderPrototype> CameraStaticShader = "CameraStatic";
    private readonly FixedEye _defaultEye = new();
    [Dependency] private IEntityManager _entityManager = default!;
    private PrisonerCollarConsoleBoundUserInterfaceState? _lastState;

    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IResourceCache _resourceCache = default!;

    private NetEntity? _selectedCollar;
    public Action<EntityUid?>? OnCameraSelected;
    public Action<NetEntity?>? OnCollarSelected;

    public Action<NetEntity>? OnDetonate;
    public Action? OnScanPair;
    public Action<NetEntity>? OnShock;
    public Action<NetEntity>? OnUnlink;
    public Action<NetEntity>? OnUnlock;

    public PrisonerCollarConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CameraView.ViewportSize = new Vector2i(96, 96);
        CameraView.Eye = _defaultEye;
        CameraView.Visible = false;

        var texture = _resourceCache.GetTexture("/Textures/Interface/Nano/square_black.png");
        CameraViewBackground.Stretch = TextureRect.StretchMode.Scale;
        CameraViewBackground.Texture = texture;
        CameraViewBackground.Visible = true;

        if (_prototypeManager.TryIndex(CameraStaticShader, out var shaderProto))
            CameraViewBackground.ShaderOverride = shaderProto.Instance().Duplicate();

        ScanButton.OnPressed += _ => OnScanPair?.Invoke();
        SearchLineEdit.OnTextChanged += _ =>
        {
            if (_lastState != null)
                PopulateList(_lastState);
        };
    }

    public void SetCameraView(IEye? eye)
    {
        if (eye != null)
        {
            CameraView.Eye = eye;
            CameraView.Visible = true;
            CameraViewBackground.Visible = false;
        }
        else
        {
            CameraView.Eye = _defaultEye;
            CameraView.Visible = false;
            CameraViewBackground.Visible = true;
        }
    }

    public void UpdateState(PrisonerCollarConsoleBoundUserInterfaceState state)
    {
        _lastState = state;
        PopulateList(state);
    }

    private void PopulateList(PrisonerCollarConsoleBoundUserInterfaceState state)
    {
        CollarListContainer.RemoveAllChildren();

        var filter = SearchLineEdit.Text.Trim().ToLowerInvariant();
        var collars = state.Collars;

        if (!string.IsNullOrEmpty(filter))
            collars = collars.Where(c => c.WearerName.ToLowerInvariant().Contains(filter)).ToList();

        if (collars.Count == 0)
        {
            _selectedCollar = null;
            OnCollarSelected?.Invoke(null);
            OnCameraSelected?.Invoke(null);
            UpdateCameraInfo(null);

            CollarListContainer.AddChild(new Label
            {
                Text = Loc.GetString("prisoner-collar-console-no-collars"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 20, 0, 0),
                FontColorOverride = Color.Gray,
            });
            return;
        }

        if (!_selectedCollar.HasValue || !collars.Any(c => c.Collar == _selectedCollar.Value))
            _selectedCollar = collars.First().Collar;

        PrisonerCollarStatusEntry? selectedEntry = null;

        foreach (var entry in collars)
        {
            var isSelected = entry.Collar == _selectedCollar;
            if (isSelected)
                selectedEntry = entry;

            var panel = new PanelContainer
            {
                Margin = new Thickness(0, 2),
                StyleClasses = { "PanelDark" },
            };

            var mainBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(8, 6),
                SeparationOverride = 4,
            };

            var headerBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 8,
            };

            var nameText = entry.IsWorn ? $"Носитель: {entry.WearerName}" : "Ошейник (не надет)";
            var nameLabel = new Label
            {
                Text = nameText,
                StyleClasses = { "LabelKeyText" },
                HorizontalExpand = true,
            };
            headerBox.AddChild(nameLabel);

            var stateColor = entry.MobState switch
            {
                "Жив" => Color.FromHex("#44ff44"),
                "Крит" => Color.FromHex("#ffaa00"),
                "Мертв" => Color.FromHex("#ff4444"),
                _ => Color.Gray,
            };

            var statusBadge = new Label
            {
                Text = entry.IsWorn ? $"[{entry.MobState}]" : "[Свободен]",
                FontColorOverride = stateColor,
            };
            headerBox.AddChild(statusBadge);

            mainBox.AddChild(headerBox);

            var detailsBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 12,
            };

            var healthText = entry.IsWorn ? $"Урон: {entry.TotalDamage}" : "Урон: --";
            detailsBox.AddChild(new Label { Text = healthText, StyleClasses = { "LabelSubText" } });

            var collarStatusText = entry.State switch
            {
                PrisonerCollarState.Active => Loc.GetString("prisoner-collar-state-active"),
                PrisonerCollarState.EmpDisabled => Loc.GetString("prisoner-collar-state-emp"),
                PrisonerCollarState.Disarmed => Loc.GetString("prisoner-collar-state-disarmed"),
                _ => Loc.GetString("prisoner-collar-state-unknown"),
            };

            var statusColor = entry.State == PrisonerCollarState.Active
                ? Color.FromHex("#ff5555")
                : Color.FromHex("#ffff55");
            detailsBox.AddChild(new Label { Text = collarStatusText, FontColorOverride = statusColor });

            mainBox.AddChild(detailsBox);

            var locText = entry.Coordinates.HasValue
                ? $"Сектор: {entry.LocationName} ({entry.Coordinates.Value.X:F1}, {entry.Coordinates.Value.Y:F1})"
                : "Сектор: Неизвестно";

            mainBox.AddChild(new Label { Text = locText, StyleClasses = { "LabelSubText" } });

            var buttonBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4,
                Margin = new Thickness(0, 4, 0, 0),
            };

            var currentCollar = entry.Collar;

            var selectBtn = new Button
            {
                Text = isSelected
                    ? Loc.GetString("prisoner-collar-console-btn-watching")
                    : Loc.GetString("prisoner-collar-console-btn-watch"),
                MinWidth = 70,
            };
            selectBtn.OnPressed += _ =>
            {
                _selectedCollar = currentCollar;
                if (_lastState != null)
                    PopulateList(_lastState);
            };
            buttonBox.AddChild(selectBtn);

            var shockBtn = new Button
            {
                Text = Loc.GetString("prisoner-collar-console-btn-shock"),
                MinWidth = 75,
            };
            shockBtn.OnPressed += _ => OnShock?.Invoke(currentCollar);
            buttonBox.AddChild(shockBtn);

            var unlockBtn = new Button
            {
                Text = Loc.GetString("prisoner-collar-console-btn-unlock"),
                MinWidth = 50,
            };
            unlockBtn.OnPressed += _ => OnUnlock?.Invoke(currentCollar);
            buttonBox.AddChild(unlockBtn);

            var unlinkBtn = new Button
            {
                Text = Loc.GetString("prisoner-collar-console-btn-unlink"),
                MinWidth = 65,
            };
            unlinkBtn.OnPressed += _ => OnUnlink?.Invoke(currentCollar);
            buttonBox.AddChild(unlinkBtn);

            var detonateBtn = new Button
            {
                Text = Loc.GetString("prisoner-collar-console-btn-detonate"),
                StyleClasses = { "Caution" },
                MinWidth = 70,
            };
            detonateBtn.OnPressed += _ => OnDetonate?.Invoke(currentCollar);
            buttonBox.AddChild(detonateBtn);

            mainBox.AddChild(buttonBox);
            panel.AddChild(mainBox);

            CollarListContainer.AddChild(panel);
        }

        UpdateCameraInfo(selectedEntry);

        if (selectedEntry != null)
        {
            var collarUid = _entityManager.GetEntity(selectedEntry.Collar);
            var wearerUid = selectedEntry.Wearer.HasValue
                ? _entityManager.GetEntity(selectedEntry.Wearer.Value)
                : (EntityUid?)null;
            var targetUid = wearerUid ?? collarUid;

            OnCollarSelected?.Invoke(selectedEntry.Collar);
            OnCameraSelected?.Invoke(targetUid);
        }
        else
        {
            OnCollarSelected?.Invoke(null);
            OnCameraSelected?.Invoke(null);
        }
    }

    private void UpdateCameraInfo(PrisonerCollarStatusEntry? entry)
    {
        if (entry == null)
        {
            CameraCoordsLabel.Text = "Координаты: N/A";
            CameraGridLabel.Text = "Сектор: N/A";
            return;
        }

        if (entry.Coordinates.HasValue)
        {
            var coords = entry.Coordinates.Value;
            CameraCoordsLabel.Text = $"Координаты: ({coords.X:F1}, {coords.Y:F1})";
            CameraGridLabel.Text = $"Сектор: {entry.LocationName}";
        }
    }
}
