- type: playTimeTracker
  id: STJobPrisoner

- type: playTimeTracker
  id: STJobHeadOfSpacePrison

- type: playTimeTracker
  id: STJobSpacePrisonOfficer

- type: playTimeTracker
  id: STJobSpacePrisonEngineer

- type: playTimeTracker
  id: STJobSpacePrisonMedic

- type: playTimeTracker
  id: STJobIAA

- type: playTimeTracker
  id: STJobGuardianNt

- type: playTimeTracker
  id: STJobBrigmedic

- type: playTimeTracker
  id: STJobJudge

- type: playTimeTracker
  id: STJobSTSecurityClown

- type: playTimeTracker
  id: STJobSTCommandMaid

- type: playTimeTracker
  id: STJobSTPartyMaker
