- type: playTimeTracker
  id: JobPrisoner

- type: playTimeTracker
  id: JobHeadOfSpacePrison

- type: playTimeTracker
  id: JobSpacePrisonOfficer

- type: playTimeTracker
  id: JobSpacePrisonEngineer

- type: playTimeTracker
  id: JobSpacePrisonMedic

- type: playTimeTracker
  id: JobIAA

- type: playTimeTracker
  id: JobGuardianNt

- type: playTimeTracker
  id: STJobBrigmedic

# Event-Restricted-Jobs

- type: playTimeTracker
  id: JobSecurityClown

- type: playTimeTracker
  id: JobCommandMaid

- type: playTimeTracker
  id: JobPartyMaker
