- type: department
  id: Prison
  name: department-Prison
  description: department-Cargo-description
  color: "#e99844"
  editorHidden: true
  roles:
  - STPRISONHeadOfPrison
  - STPRISONEngineer
  - STPRISONMedic
  - STPRISONOfficer
  - STPRISONPrisoner

- type: department
  id: STJuridical
  name: stories-department-Juridical
  description: stories-department-Juridical-description
  color: "#6d5d53"
  roles:
  - STIAA
  - Lawyer
  - STJudge
