- type: entity
  name: сумка для плодов
  id: STProduceBag
  parent: PlantBag
  description: Сумка для ботаников, чтобы легко переносить свои огромные урожаи.
  components:
  - type: Sprite
    sprite: _Stories/Objects/Specific/Hydroponics/Equipment/produce_bag.rsi
    state: icon
  - type: Storage
    grid:
    - 0,0,7,4
    maxItemSize: Small
    quickInsert: true
    areaInsert: true
    whitelist:
      components:
        - Produce